#!/bin/bash
# Golden Router One-Click Installer for Linux/macOS
# This script automates the entire setup process

set -e

SKIP_DEPS=false
SKIP_BUILD=false
DEV_MODE=false

# Parse arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --skip-deps) SKIP_DEPS=true ;;
        --skip-build) SKIP_BUILD=true ;;
        --dev) DEV_MODE=true ;;
        *) echo "Unknown parameter: $1"; exit 1 ;;
    esac
    shift
done

echo "========================================"
echo "  Golden Router One-Click Installer"
echo "========================================"
echo ""

# Check if Node.js is installed
echo "Checking Node.js installation..."
if ! command -v node &> /dev/null; then
    echo "âœ— Node.js not found. Please install Node.js >= 22.22.2"
    echo "Download from: https://nodejs.org/"
    exit 1
fi

NODE_VERSION=$(node --version)
echo "âœ“ Node.js $NODE_VERSION found"

# Check Node.js version requirement
REQUIRED_VERSION="22.22.2"
if [ "$(printf '%s\n' "$REQUIRED_VERSION" "${NODE_VERSION#v}" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]; then
    echo "âœ— Node.js version $NODE_VERSION is too old. Required: >= 22.22.2"
    exit 1
fi

# Check if Git is installed
echo "Checking Git installation..."
if ! command -v git &> /dev/null; then
    echo "âœ— Git not found. Please install Git"
    echo "On Ubuntu/Debian: sudo apt-get install git"
    echo "On macOS: brew install git"
    exit 1
fi

echo "âœ“ Git found"

# Clone or update repository
REPO_URL="https://github.com/EfkaStudio-prd/G-ROUTER.git"
INSTALL_DIR="$HOME/golden-router"

echo "Setting up Golden Router in $INSTALL_DIR..."

if [ -d "$INSTALL_DIR" ]; then
    echo "Directory exists. Updating..."
    cd "$INSTALL_DIR"
    git pull origin main
else
    echo "Cloning repository..."
    git clone "$REPO_URL" "$INSTALL_DIR"
    cd "$INSTALL_DIR"
fi

# Install dependencies
if [ "$SKIP_DEPS" = false ]; then
    echo "Installing dependencies..."
    npm install
    echo "âœ“ Dependencies installed"
fi

# Generate secrets if .env.local doesn't exist
ENV_FILE="$INSTALL_DIR/.env.local"
if [ ! -f "$ENV_FILE" ]; then
    echo "Generating secrets..."
    
    # Generate JWT secret
    JWT_SECRET=$(openssl rand -base64 48)
    
    # Generate API key secret
    API_KEY_SECRET=$(openssl rand -hex 32)
    
    # Create .env.local
    cat > "$ENV_FILE" << EOF
# â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”
# â”‚                         Golden Router â€” .env.local                             â”‚
# â”‚  Auto-generated by installer. DO NOT COMMIT to git.                         â”‚
# â””â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”˜

# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# 1. REQUIRED SECRETS
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
JWT_SECRET=$JWT_SECRET
API_KEY_SECRET=$API_KEY_SECRET
INITIAL_PASSWORD=CHANGEME

# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# 2. STORAGE & DATABASE
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
DATA_DIR=~/.golden-router
STORAGE_ENCRYPTION_KEY=
STORAGE_ENCRYPTION_KEY_VERSION=v1
DISABLE_SQLITE_AUTO_BACKUP=false
REDIS_URL=redis://localhost:6379

# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# 3. NETWORK & PORTS
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
PORT=20128
GOLDENROUTER_USE_TURBOPACK=1

# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# 4. CLOUD SYNC (Supabase + Clerk) - Optional
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# Uncomment and fill these to enable cloud sync
# NEXT_PUBLIC_SUPABASE_URL=
# NEXT_PUBLIC_SUPABASE_ANON_KEY=
# NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=
# CLERK_SECRET_KEY=
# CLERK_WEBHOOK_SECRET=
# CLOUD_SYNC_ENABLED=false
EOF
    
    echo "âœ“ Secrets generated and saved to .env.local"
    echo "  IMPORTANT: Change INITIAL_PASSWORD before first use!"
else
    echo "âœ“ .env.local already exists, skipping secret generation"
fi

# Build project
if [ "$SKIP_BUILD" = false ]; then
    echo "Building Golden Router..."
    npm run build
    echo "âœ“ Build completed"
fi

# Install CLI globally
echo "Installing Golden Router CLI globally..."
npm install -g . || echo "âš  Failed to install CLI globally, but you can still run from source"
echo "âœ“ CLI installed globally"

echo ""
echo "========================================"
echo "  Installation Complete!"
echo "========================================"
echo ""
echo "To start Golden Router:"
echo "  From source: npm run dev"
echo "  From CLI:     golden-router"
echo ""
echo "Dashboard URL: http://localhost:20128"
echo ""
echo "IMPORTANT:"
echo "1. Change INITIAL_PASSWORD in .env.local"
echo "2. Configure your AI provider API keys in the dashboard"
echo "3. For cloud sync, fill in Supabase and Clerk credentials in .env.local"
echo ""

if [ "$DEV_MODE" = true ]; then
    echo "Starting in development mode..."
    npm run dev
fi
