# Golden Router One-Click Installer for Windows
# This script automates the entire setup process

param(
    [switch]$SkipDeps,
    [switch]$SkipBuild,
    [switch]$DevMode
)

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Golden Router One-Click Installer" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if Node.js is installed
Write-Host "Checking Node.js installation..." -ForegroundColor Yellow
try {
    $nodeVersion = node --version
    Write-Host "[OK] Node.js $nodeVersion found" -ForegroundColor Green
} catch {
    Write-Host "[ERROR] Node.js not found. Please install Node.js >= 22.22.2" -ForegroundColor Red
    Write-Host "Download from: https://nodejs.org/" -ForegroundColor Cyan
    exit 1
}

# Check Node.js version requirement
$requiredVersion = [version]"22.22.2"
$currentVersion = [version]($nodeVersion -replace 'v', '')
if ($currentVersion -lt $requiredVersion) {
    Write-Host "[ERROR] Node.js version $nodeVersion is too old. Required: >= 22.22.2" -ForegroundColor Red
    exit 1
}

# Check if Git is installed
Write-Host "Checking Git installation..." -ForegroundColor Yellow
try {
    git --version | Out-Null
    Write-Host "[OK] Git found" -ForegroundColor Green
} catch {
    Write-Host "[ERROR] Git not found. Please install Git" -ForegroundColor Red
    Write-Host "Download from: https://git-scm.com/" -ForegroundColor Cyan
    exit 1
}

# Clone or update repository
$repoUrl = "https://github.com/EfkaStudio-prd/G-ROUTER.git"
$installDir = "$env:USERPROFILE\golden-router"

Write-Host "Setting up Golden Router in $installDir..." -ForegroundColor Yellow

if (Test-Path $installDir) {
    Write-Host "Directory exists. Updating..." -ForegroundColor Yellow
    Set-Location $installDir
    git pull origin main
} else {
    Write-Host "Cloning repository..." -ForegroundColor Yellow
    git clone $repoUrl $installDir
    Set-Location $installDir
}

# Install dependencies
if (-not $SkipDeps) {
    Write-Host "Installing dependencies..." -ForegroundColor Yellow
    npm install
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[ERROR] Failed to install dependencies" -ForegroundColor Red
        exit 1
    }
    Write-Host "[OK] Dependencies installed" -ForegroundColor Green
}

# Generate secrets if .env.local doesn't exist
$envFile = "$installDir\.env.local"
if (-not (Test-Path $envFile)) {
    Write-Host "Generating secrets..." -ForegroundColor Yellow
    
    # Generate JWT secret
    $jwtSecret = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 48 | ForEach-Object { [char]$_ })
    
    # Generate API key secret
    $apiKeySecret = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 64 | ForEach-Object { [char]$_ })
    
    # Create .env.local
    $envContent = @"
# Golden Router - .env.local
# Auto-generated by installer. DO NOT COMMIT to git.

# 1. REQUIRED SECRETS
JWT_SECRET=$jwtSecret
API_KEY_SECRET=$apiKeySecret
INITIAL_PASSWORD=CHANGEME

# 2. STORAGE & DATABASE
DATA_DIR=~/.golden-router
STORAGE_ENCRYPTION_KEY=
STORAGE_ENCRYPTION_KEY_VERSION=v1
DISABLE_SQLITE_AUTO_BACKUP=false
REDIS_URL=redis://localhost:6379

# 3. NETWORK & PORTS
PORT=20128
GOLDENROUTER_USE_TURBOPACK=1
"@
    $envContent | Out-File -FilePath $envFile -Encoding UTF8

    Write-Host "[OK] Secrets generated and saved to .env.local" -ForegroundColor Green
    Write-Host "  IMPORTANT: Change INITIAL_PASSWORD before first use!" -ForegroundColor Yellow
} else {
    Write-Host "[OK] .env.local already exists, skipping secret generation" -ForegroundColor Green
}

# Build project
if (-not $SkipBuild) {
    Write-Host "Building Golden Router..." -ForegroundColor Yellow
    npm run build
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[ERROR] Build failed" -ForegroundColor Red
        exit 1
    }
    Write-Host "[OK] Build completed" -ForegroundColor Green
}

# Install CLI globally
Write-Host "Installing Golden Router CLI globally..." -ForegroundColor Yellow
npm install -g .
if ($LASTEXITCODE -ne 0) {
    Write-Host "[WARN] Failed to install CLI globally, but you can still run from source" -ForegroundColor Yellow
} else {
    Write-Host "[OK] CLI installed globally" -ForegroundColor Green
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Installation Complete!" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "To start Golden Router:" -ForegroundColor Yellow
Write-Host "  From source: npm run dev" -ForegroundColor White
Write-Host "  From CLI:     golden-router" -ForegroundColor White
Write-Host ""
Write-Host "Dashboard URL: http://localhost:20128" -ForegroundColor Cyan
Write-Host ""
Write-Host "IMPORTANT:" -ForegroundColor Red
Write-Host "1. Change INITIAL_PASSWORD in .env.local" -ForegroundColor White
Write-Host "2. Configure your AI provider API keys in the dashboard" -ForegroundColor White

Write-Host ""

if ($DevMode) {
    Write-Host "Starting in development mode..." -ForegroundColor Yellow
    npm run dev
}
